A = int(input("Informe a quantidade de votos válidos para o candidato A: "))
B = int(input("Informe a quantidade de votos válidos para o candidato B: "))
C = int(input("Informe a quantidade de votos válidos para o candidato C: "))
branco = int(input("Informe a quantidade de votos em branco: "))
nulo = int(input("Informe a quantidade de votos nulo: "))
total = A + B + C + branco + nulo
percvalido = int(((A + B + C)/total)*100)
percA = int((A/total)*100)
percB = int((B/total)*100)
percC = int((C/total)*100)
percnulo = int((nulo/total)*100)
percbranco = int((branco/total)*100)
print(f"Numero total de eleitores igual a {total}")
print(f"Percentual de votos válidos em relação a quantidade de eleitores: {percvalido}%")
print(f"Percentual de votos do candidato A em relação a quantidade de eleitores: {percA}%")
print(f"Percentual de votos do candidato B em relação a quantidade de eleitores: {percB}%")
print(f"Percentual de votos do candidato C em relação a quantidade de eleitores: {percC}%")
print(f"Percentual de votos nulo em relação a quantidade de eleitores: {percnulo}%")
print(f"Percentual de votos em branco em relação a quantidade de eleitores: {percbranco}%")