n = int(input('Informe um número: '))
print('Unidade: {}'.format(n%10))
print('Dezena: {}'.format((n // 10) % 10))
print('Centena: {}'.format((n // 100) % 10))
print('Milhar: {}'.format((n // 1000) % 10))
