nome = str(input('Informe o seu nome completo: '))
nomeMai = nome.upper()
nomeMin = nome.lower()
nomecont = len(nome.replace(' ', ''))
primeiroN = len(nome.split()[0])
print('O nome com letras maiusculas fica {}'.format(nomeMai))
print('O nome com letras minusculas fica {}'.format(nomeMin))
print('Aparecem {} letras ao todo'.format(nomecont))
print('O primeiro nome tem {} letras'.format(primeiroN))